### ISSUE TITLE
JsonSyntaxException thrown

### ISSUE THREAD

**Issue by fouadkada** [gleezr/Slink#2]
Hey,

the following error happens more or less randomly, I couldn't pinpoint a solid way to replicate it.
sometime when i restart the application in debug mode the error happens sometimes it does not; but when it does, the application fails to start all the time, so when the error happens the application is not able to start anymore, I have to uninstall and install again.

below is a stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: SharedPreferencesImpl-load
                  Process: com.example.app, PID: 21199
                  com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
                      at com.google.gson.Gson.fromJson(Gson.java:899)
                      at com.google.gson.Gson.fromJson(Gson.java:852)
                      at com.google.gson.Gson.fromJson(Gson.java:801)
                      at com.gleezr.slink.Slink.loadFromDisk(Slink.java:177)
                      at com.gleezr.slink.Slink.access$000(Slink.java:57)
                      at com.gleezr.slink.Slink$1.run(Slink.java:113)
                   Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
                      at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
                      at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
                      at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
                      at com.google.gson.Gson.fromJson(Gson.java:887)
                      at com.google.gson.Gson.fromJson(Gson.java:852) 
                      at com.google.gson.Gson.fromJson(Gson.java:801) 
                      at com.gleezr.slink.Slink.loadFromDisk(Slink.java:177) 
                      at com.gleezr.slink.Slink.access$000(Slink.java:57) 
                      at com.gleezr.slink.Slink$1.run(Slink.java:113) 
```

**Comment by yanivgal** [comment]
What is the data you're trying to save?

**Comment by Sergioct** [comment]
I have the same problem saving a json string.

**Comment by tomrum** [comment]
I have the same problem also:

E/AndroidRuntime: FATAL EXCEPTION: SharedPreferencesImpl-load
    Process: com.*.* PID: 16304
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:899)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.gleezr.slink.Slink.loadFromDisk(Slink.java:177)
        at com.gleezr.slink.Slink.access$000(Slink.java:57)
        at com.gleezr.slink.Slink$1.run(Slink.java:113)
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:852) 
        at com.google.gson.Gson.fromJson(Gson.java:801) 
        at com.gleezr.slink.Slink.loadFromDisk(Slink.java:177) 
        at com.gleezr.slink.Slink.access$000(Slink.java:57) 
        at com.gleezr.slink.Slink$1.run(Slink.java:113) 

Going to uninstall this library!

**Comment by fouadkada** [comment]
I also ended up ditching this library

**Comment by tomrum** [comment]
fouadkada Please let me know if you find a stable way to properly encrypt shared prefs, thanks

**Comment by fouadkada** [comment]
have a look at https://github.com/scottyab/secure-preferences 
i havent used it but it seems the project is still maintained

**Comment by tomrum** [comment]
fouadkada Cheers! :-)
